name: milk2

channels:
  - conda-forge
  - defaults

dependencies:
  - pip=22.1.2
  - python=3.8
  - tqdm=4.64.0
  - prettytable=3.3.0

  # pip packages
  - pip:
    - git+https://github.com/lanl/MILK.git
