name: rietveld

channels:
  - defaults
  - conda-forge
  
dependencies:
  #Base MILK
  - tqdm
  - pip
  - prettytable
  - python=3.9
  - pandas
  - pydantic
  - seaborn
  - pyfai
  - matplotlib
  - pyopencl
  - opencv
  - pyqtgraph
  - autopep8
  - git
  - pytest

  # Spotlight
  - klepto=0.2.2
  - numpy=1.23.0
  # - openmpi
  # - mpi4py
  - jupyter=1.0.0
  - nbsphinx=0.8.9
  - sphinx=5.0.2
  - sphinxcontrib-programoutput=0.16
  - scipy=1.8.1
  - scikit-learn=1.1.2

  # pip packages
  - pip:
    #MILK github installation
    - -e ../
    #Spotlight
    - git+https://github.com/lanl/spotlight.git@v0.10.2
    - mystic==0.3.9
    - pyina==0.2.6
    - pathos==0.2.9
